// Copyright 2025, Reclaim Protocol. Use of this source code is governed by a license that can be found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:reclaim_verifier_module/src/pigeon/schema.pigeon.dart';


// ignore: unused_element
class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ReclaimApiVerificationExceptionType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ReclaimApiVerificationRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ReclaimApiVerificationException) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ReclaimApiVerificationResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ReclaimApiVerificationExceptionType.values[value];
      case 130: 
        return ReclaimApiVerificationRequest.decode(readValue(buffer)!);
      case 131: 
        return ReclaimApiVerificationException.decode(readValue(buffer)!);
      case 132: 
        return ReclaimApiVerificationResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
