# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ReclaimExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReclaimExample

  target 'ReclaimExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReclaimExampleUITests' do
    # Pods for testing
  end

end
