// Copyright 2025, Reclaim Protocol. Use of this source code is governed by a license that can be found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum ReclaimApiVerificationExceptionType {
  unknown,
  sessionExpired,
  verificationDismissed,
  verificationFailed,
  verificationCancelled,
}

class ReclaimApiVerificationRequest {
  ReclaimApiVerificationRequest({
    required this.appId,
    required this.providerId,
    required this.secret,
    required this.signature,
    this.timestamp,
    required this.context,
    required this.sessionId,
    required this.parameters,
    required this.debug,
    required this.hideLanding,
    required this.autoSubmit,
    required this.acceptAiProviders,
    this.webhookUrl,
  });

  String appId;

  String providerId;

  String secret;

  String signature;

  String? timestamp;

  String context;

  String sessionId;

  Map<String, String> parameters;

  bool debug;

  bool hideLanding;

  bool autoSubmit;

  bool acceptAiProviders;

  String? webhookUrl;

  Object encode() {
    return <Object?>[
      appId,
      providerId,
      secret,
      signature,
      timestamp,
      context,
      sessionId,
      parameters,
      debug,
      hideLanding,
      autoSubmit,
      acceptAiProviders,
      webhookUrl,
    ];
  }

  static ReclaimApiVerificationRequest decode(Object result) {
    result as List<Object?>;
    return ReclaimApiVerificationRequest(
      appId: result[0]! as String,
      providerId: result[1]! as String,
      secret: result[2]! as String,
      signature: result[3]! as String,
      timestamp: result[4] as String?,
      context: result[5]! as String,
      sessionId: result[6]! as String,
      parameters: (result[7] as Map<Object?, Object?>?)!.cast<String, String>(),
      debug: result[8]! as bool,
      hideLanding: result[9]! as bool,
      autoSubmit: result[10]! as bool,
      acceptAiProviders: result[11]! as bool,
      webhookUrl: result[12] as String?,
    );
  }
}

class ReclaimApiVerificationException {
  ReclaimApiVerificationException({
    required this.message,
    required this.stackTraceAsString,
    required this.type,
  });

  String message;

  String stackTraceAsString;

  ReclaimApiVerificationExceptionType type;

  Object encode() {
    return <Object?>[
      message,
      stackTraceAsString,
      type,
    ];
  }

  static ReclaimApiVerificationException decode(Object result) {
    result as List<Object?>;
    return ReclaimApiVerificationException(
      message: result[0]! as String,
      stackTraceAsString: result[1]! as String,
      type: result[2]! as ReclaimApiVerificationExceptionType,
    );
  }
}

class ReclaimApiVerificationResponse {
  ReclaimApiVerificationResponse({
    required this.sessionId,
    required this.didSubmitManualVerification,
    required this.proofs,
    this.exception,
  });

  String sessionId;

  bool didSubmitManualVerification;

  List<Map<String, dynamic>> proofs;

  ReclaimApiVerificationException? exception;

  Object encode() {
    return <Object?>[
      sessionId,
      didSubmitManualVerification,
      proofs,
      exception,
    ];
  }

  static ReclaimApiVerificationResponse decode(Object result) {
    result as List<Object?>;
    return ReclaimApiVerificationResponse(
      sessionId: result[0]! as String,
      didSubmitManualVerification: result[1]! as bool,
      proofs: (result[2] as List<Object?>?)!.cast<Map<String, dynamic>>(),
      exception: result[3] as ReclaimApiVerificationException?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ReclaimApiVerificationExceptionType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ReclaimApiVerificationRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ReclaimApiVerificationException) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ReclaimApiVerificationResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ReclaimApiVerificationExceptionType.values[value];
      case 130: 
        return ReclaimApiVerificationRequest.decode(readValue(buffer)!);
      case 131: 
        return ReclaimApiVerificationException.decode(readValue(buffer)!);
      case 132: 
        return ReclaimApiVerificationResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class ReclaimModuleApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<ReclaimApiVerificationResponse> startVerification(ReclaimApiVerificationRequest request);

  Future<bool> ping();

  static void setUp(ReclaimModuleApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.startVerification$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.startVerification was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ReclaimApiVerificationRequest? arg_request = (args[0] as ReclaimApiVerificationRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.startVerification was null, expected non-null ReclaimApiVerificationRequest.');
          try {
            final ReclaimApiVerificationResponse output = await api.startVerification(arg_request!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.ping$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final bool output = await api.ping();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class ReclaimApi {
  /// Constructor for [ReclaimApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ReclaimApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> ping() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.reclaim_verifier_module.ReclaimApi.ping$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}
